language: python

python:
  - "2.7"

install:
  - pip install coverage
  - pip install coveralls

script: 
  - coverage run --include=barracks_sdk/* setup.py test
  - coverage report

after_success:
  - coveralls
